# Generated by Django 2.2.2 on 2019-08-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookCompanionCategoryList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('maincategory', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'list_of_category',
            },
        ),
        migrations.CreateModel(
            name='TextbookCompanionSubCategoryList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('subcategory_id', models.IntegerField()),
                ('subcategory', models.CharField(max_length=255)),
                ('maincategory_id', models.IntegerField()),
            ],
            options={
                'db_table': 'list_of_subcategory',
            },
        ),
    ]
